[package]
name = "demo-a"
version.workspace = true
edition.workspace = true

[dependencies]
renamed_once_cell = { workspace = true, optional = true }

[features]
renamed_once_cell = ["dep:renamed_once_cell"]
